---
title: "Press Coverage"
format: 
  html:
    toc: false
    page-layout: article
---

## Press and Review Article Coverage

### 2022

**Evolution Gone Wild: What makes seadragons so strange** • *New York Times*

### 2021

**UO faculty members receives grant to better understand symbiosis** • *Around the O*

**Genome Spotlight: Mandarinfish (Synchiropus splendidus)** • *The Scientist*

**Study looks at how the human microbiome varies with location** • *Around the O*

**Research project examines male pregnancy and microbes in fish** • *Around the O*

### 2020

**Gift will rapidly expand UO, state COVID-19 testing** • *Around the O*

**Experimental COVID-19 test at UO replaces nasal swab with saliva sample** • *OPB Blog*

**New grant will expand COVID-19 testing in Latinx communities** • *Around the O*

### 2019

**UO, OHSU will partner on opioid research with $10M grant** • *Around the O*

**Three UO undergraduates awarded Goldwater Scholarships** • *Around the O*

**Knight Campus Program Gives Undergrads Real-World Research Experience** • *Around the O*

### 2018

**UO postdoc solves mystery of isolated Atlantic island birds** • *Around the O*

**How an earthquake shook up stickleback genomes** • *Genes to Genomes GSA Blog* • [Link](http://genestogenomes.org/how-an-earthquake-shook-up-stickleback-genomes/)

### 2017

**Hold your (sea)horses – here's the pipefish genome** • *BioMed Central* • [Link](https://blogs.biomedcentral.com/on-biology/2016/12/20/pipefishgenome/)

### 2016

**Oregon researchers publish reference genome of gulf pipefish** • *EurekAlert, AAAS*

**UO team unspools the genome of a seahorse relative** • *Around the O*

**UO's Cresko chosen as fellow of world's largest scientific group** • *Around the O*

**Harnessing the power of RADseq for ecological and evolutionary genomics** • Andrews et al. • *Nature Reviews Genetics* • [Link](https://www.nature.com/articles/nrg.2015.28)

**Earthquakes and rapid evolution** • *The Molecular Ecologist* • [Link](https://www.molecularecologist.com/2016/01/earthquakes-and-rapid-evolution/)

### 2015

**Our 2010 PloS Genetics paper was chosen one of the 10 most important papers ever in PLoS Genetics** • *PLoS Genetics*

**A decad(e) of reasons to contribute to a PLoS community-run Journal** • Copenhaver & Barsh • *PLoS Genetics* • [Link](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005557)\
*Commentary on our 2010 paper (Hohenlohe, Bassham et al.) chosen as one of the 10 most important papers in PLoS Genetics' first decade*

**Interview on Oregon Public Broadcasting's Think Out Loud about stickleback evolution** • *OPB* • [Link](https://www.opb.org/radio/programs/thinkoutloud/segment/evolution-can-happen-quicker-than-previously-thought/)

**Small fish takes evolution fast track** • Interview with Dr. Susie Bassham • *Scientific American* • [Link](https://www.scientificamerican.com/video/fish-on-evolution-s-fast-track/)

**Small fish species evolved rapidly following 1964 Alaska earthquake** • *ScienceDaily* • [Link](https://www.sciencedaily.com/releases/2015/12/151214165724.htm)

**Catastrophic Earthquake Drove Fish Evolution In Just 50 Years** • Fang, J. • *IFL Science* • [Link](https://www.iflscience.com/plants-and-animals/catastrophic-earthquake-drove-fish-evolution-just-50-years/)

**Interview on Jefferson Public Radio about stickleback evolution** • *OPB*

**Earthquake forced rapid evolution in fish** • Kiger, P.J. • *Discovery News* • [Link](https://www.seeker.com/earthquake-forced-rapid-evolution-in-fish-1770617657.html)

**Small fish species evolved rapidly following 1964 Alaska earthquake** • *Phys.Org* • [Link](https://phys.org/news/2015-12-small-fish-species-evolved-rapidly.html)

**Big Earthquake jolted fish into fast evolution** • *Futurity* • [Link](https://www.futurity.org/threespine-stickleback-fish-evolution-1070162-2/)

**Stickleback fish evolved rapidly to living in freshwater ponds following major earthquake** • Mathewson, S. • *Nature World News* • [Link](https://www.natureworldnews.com/articles/18779/20151215/stickleback-fish-rapidly-evolved-living-freshwater-ponds-following-major-earthquake.htm)

**UO-led study shows fish evolved rapidly after 1964 Alaska quake** • *Around the O*

**Genetics journal names paper led by UO's Cresko as among its Top 10 of all time** • *Around the O*

### 2013

**Julian Catchen helps us dig into Stacks** • *The Molecular Ecologist* • [Link](https://www.molecularecologist.com/2013/04/qa-julian-catchen-helps-us-dig-into-stacks/)

### 2011

**Fast-Forwarding Mendel** • *Around the O*

**RAD-Tagging is demystifying genome sequencing** • *NewsWise* • [Link](https://www.newswise.com/articles/rad-tagging-technology-is-demystifying-genome-sequencing)

**Using DNA to Reveal a Mosquito's History** • *Science* 331:1006-1007

### 2010

**Adaptation Genomics: the next generation** • Stapley et al. • *Trends in Ecology and Evolution* 25: 705-712 • [Link](https://www.ncbi.nlm.nih.gov/pubmed/20952088)

**Genomic Study IDs Parallel Adaptations in Independent Stickleback Populations** • *GenomeWeb* • [Link](https://www.genomeweb.com/sequencing/genomic-study-ids-parallel-adaptations-independent-stickleback-populations)

**Genomic Study IDs Parallel Adaptations in Independent Stickleback Pops** • *GenomeWeb Daily*

**Stickleback Genomes Shining Bright Light on Evolution** • *ScienceDaily* • [Link](https://www.sciencedaily.com/releases/2010/02/100225214757.htm)

**News from the field: Stickleback Genomes Shining Bright Light on Evolution** • *NSF Press Release* • [Link](https://www.nsf.gov/news/news_summ.jsp?cntn_id=116516)

**The parallel lives of threespine stickleback** • *Discover Magazine Online* • [Link](https://www.discovermagazine.com/health/the-parallel-lives-of-threespine-stickleback)

**News from the field: Genetic Structure of First Animal to Show Evolutionary Response to Climate Change Determined** • *NSF Press Release* • [Link](https://www.nsf.gov/news/news_summ.jsp?cntn_id=117577)

**Mosquitoes: Genetic Structure of First Animal to Show Evolutionary Response to Climate Change Determined** • *ScienceDaily* • [Link](https://www.sciencedaily.com/releases/2010/08/100824132357.htm)

### 2009

**Biology's next top model** • Maher, B. • *Nature* 458: 695-698 • [Link](https://www.nature.com/articles/458695a)

### 2008

**Science & Swing: Steve Perry's career a blend of swing, ska, punk…and evolutionary developmental biology** • *Around the O*

**Fitness in a changing world** • *NSF Press Release* • [Link](https://www.nsf.gov/news/news_summ.jsp?cntn_id=112436)

### 2006

**Macroevolution: Alive and well in sticklebacks** • Platt, J.E. • *The American Biology Teacher* 68: 5-6 • [Link](https://abt.ucpress.edu/content/68/1/5)

**Reproductive Toxicity: New Take on Perchlorate Effects** • *Environmental Health Perspectives* • [Link](https://ehp.niehs.nih.gov/doi/10.1289/ehp.114-a637a)

**Macho moms: Perchlorate pollutant masculinizes fish** • Raloff, J.A. • *Science News* 170(7) • [Link](https://www.sciencenews.org/article/macho-moms-perchlorate-pollutant-masculinizes-fish)

### 2004

**Evolution in parallel: new insights from a classic system** • Foster, S.A. & J.A. Baker • *Trends in Ecology and Evolution* 19: 456-459 • [Link](https://www.sciencedirect.com/science/article/pii/S0169534704002010?via%3Dihub)

**Evolutionary Biology, Changing fish's bony armor in the wink of a gene** • Pennisi, E. • *Science* 304: 1737-1739 • [Link](https://science.sciencemag.org/content/304/5678/1736)

**Big cross lands sticklebacks in the spotlight** • Secko, D. • *The Scientist* 18(21): 16 • [Link](https://www.the-scientist.com/research/big-cross-lands-sticklebacks-in-the-spotlight-49390)

**Morphological Diversity: Taking the spine out of three-spine stickleback** • Tickle, C. & N. Cole • *Current Biology* 14(11): 422-424 • [Link](https://reader.elsevier.com/reader/sd/pii/S0960982204003616?token=0E604FC40746B442934DA23D7C781117D0BE0E3F77E12E665CBCD8B5D0C9AE8D67DB3CD48E5FA98FB46BD41642B89C01)
