---
title: "Talks"
page-layout: full
toc: false
---

<style>
.talk-item {
  display: flex;
  margin-bottom: 1.5rem;
  align-items: flex-start;
}

.talk-title {
  flex: 0 0 25%;
  padding-right: 2rem;
  font-weight: 500;
}

.talk-details {
  flex: 0 0 75%;
  padding-left: 1rem;
  border-left: 1px solid #e5e7eb;
}

.talk-details strong {
  display: block;
  margin-bottom: 0.25rem;
}

@media (max-width: 768px) {
  .talk-item {
    flex-direction: column;
  }
  
  .talk-title {
    flex: 1 1 100%;
    padding-right: 0;
    margin-bottom: 0.5rem;
  }
  
  .talk-details {
    flex: 1 1 100%;
    padding-left: 0;
    border-left: none;
    padding-top: 0.5rem;
    border-top: 1px solid #e5e7eb;
  }
}
</style>

::: {.talks-container}

## 2025

::: {.talk-item}
::: {.talk-title}
University of Arizona  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Ecology and Evolutionary Biology**  
Tucson, AZ | 2025  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Western Washington University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
Bellingham, WA | 2025  
Invited Speaker
:::
:::

## 2023

::: {.talk-item}
::: {.talk-title}
University of Oregon  
*Departmental Seminar*
:::
::: {.talk-details}
**Institute of Ecology and Evolution**  
Eugene, OR | 2023  
Invited Speaker
:::
:::

## 2021

::: {.talk-item}
::: {.talk-title}
Aesthetic and Organic Complexity  
*Public Seminar*
:::
::: {.talk-details}
**Public Presentation**  
Boston, MA | 2021  
Public Lecture
:::
:::

::: {.talk-item}
::: {.talk-title}
Bern University  
*Departmental Seminar*
:::
::: {.talk-details}
**Institute of Ecology and Evolution**  
Bern, Switzerland | 2021  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Cardiff University  
*Departmental Seminar*
:::
::: {.talk-details}
**School of Biosciences**  
Cardiff, Wales, UK | 2021  
Invited Speaker
:::
:::

## 2020

::: {.talk-item}
::: {.talk-title}
ARCS Foundation  
*Public Presentation*
:::
::: {.talk-details}
**Achievement Rewards for College Scientists**  
Portland, OR | 2020  
Public Lecture
:::
:::

## 2019

::: {.talk-item}
::: {.talk-title}
University of Iowa  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
Iowa City, IA | 2019  
Invited Speaker
:::
:::

## 2018

::: {.talk-item}
::: {.talk-title}
Washington University  
*Graduate Student Invited*
:::
::: {.talk-details}
**Annual Graduate Student Invited Speaker**  
St. Louis, MO | 2018  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Northern Arizona University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biological Sciences**  
Flagstaff, AZ | 2018  
Invited Speaker
:::
:::

## 2017

::: {.talk-item}
::: {.talk-title}
Stowers Institute  
*Research Seminar*
:::
::: {.talk-details}
**Stowers Institute for Medical Research**  
Kansas City, MO | 2017  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Humboldt State University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biological Sciences**  
Arcata, CA | 2017  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Eugene Natural History Society  
*Public Seminar*
:::
::: {.talk-details}
**Public Presentation**  
Eugene, OR | 2017  
Public Lecture
:::
:::

## 2016

::: {.talk-item}
::: {.talk-title}
CGRB Distinguished Lecture  
*Keynote*
:::
::: {.talk-details}
**Oregon State University Center for Genome Research and Biocomputing**  
Corvallis, OR | 2016  
Keynote Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Lund University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
Lund, Sweden | 2016  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
ARCS Foundation  
*Public Presentation*
:::
::: {.talk-details}
**Achievement Rewards for College Scientists**  
Portland, OR | 2016  
Public Lecture
:::
:::

## 2015

::: {.talk-item}
::: {.talk-title}
Donald W. Hagen Keynote  
*International Conference*
:::
::: {.talk-details}
**International Stickleback Conference**  
Leicester, England | 2015  
Keynote Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Kansas  
*Graduate Student Speaker*
:::
::: {.talk-details}
**Annual Graduate Student Speaker Series**  
Lawrence, KS | 2015  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Oregon  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
Eugene, OR | 2015  
Invited Speaker
:::
:::

## 2014

::: {.talk-item}
::: {.talk-title}
Genomics and Adaptation  
*Keynote*
:::
::: {.talk-details}
**Genomics and Adaptation in an NGS Age, Lund University**  
Lund, Sweden | 2014  
Keynote Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Charles Henry Gilber Lecture  
*Named Lecture*
:::
::: {.talk-details}
**Gilbert Icthyological Meeting**  
Corvallis, OR | 2014  
Keynote Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
IGERT Capstone  
*Plenary*
:::
::: {.talk-details}
**IGERT Capstone Conference, University of Arizona**  
Tucson, AZ | 2014  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Aquatic Model Organism  
*Plenary*
:::
::: {.talk-details}
**Aquatic Model Organism Meeting**  
Austin, TX | 2014  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
AGBT Conference  
*Plenary*
:::
::: {.talk-details}
**Advances in Genomics and BioTechnology**  
Panacea, FL | 2014  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Oregon State University  
*Departmental Seminar*
:::
::: {.talk-details}
**Integrative Biology**  
Corvallis, OR | 2014  
Invited Speaker
:::
:::

## 2013

::: {.talk-item}
::: {.talk-title}
Aquatic Model Organism  
*Plenary*
:::
::: {.talk-details}
**Aquatic Model Organism Meeting**  
Milwaukee, WI | 2013  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
GENECO Summer Conference  
*Plenary*
:::
::: {.talk-details}
**Lund University**  
Lund, Sweden | 2013  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
European Society for Evolutionary Biology  
*Plenary*
:::
::: {.talk-details}
**ESEB Conference**  
Lisbon, Portugal | 2013  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Alaska  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology and Wildlife**  
Fairbanks, AK | 2013  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Oregon State University  
*Marine Station Seminar*
:::
::: {.talk-details}
**Hatfield Marine Science Center**  
Newport, OR | 2013  
Invited Speaker
:::
:::

## 2012

::: {.talk-item}
::: {.talk-title}
West Coast Salmonid  
*Plenary*
:::
::: {.talk-details}
**West Coast Salmonid Conference**  
Davis, CA | 2012  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Ecological Genomics  
*Anniversary Plenary*
:::
::: {.talk-details}
**10th Anniversary Ecological Genomics Conference**  
St. Louis, MO | 2012  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Plant and Animal Genome  
*Plenary*
:::
::: {.talk-details}
**PAG Conference**  
San Diego, CA | 2012  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
PanAsian Genomics  
*Plenary*
:::
::: {.talk-details}
**PanAsian Genomics Conference, Silliman University**  
Philippines | 2012  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Oregon  
*Physics Seminar*
:::
::: {.talk-details}
**Department of Physics**  
Eugene, OR | 2012  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Institut Jacques Monod  
*Research Seminar*
:::
::: {.talk-details}
**Institut Jacques Monod**  
Paris, France | 2012  
Invited Speaker
:::
:::

## 2011

::: {.talk-item}
::: {.talk-title}
Next Generation Genomics  
*Keynote*
:::
::: {.talk-details}
**Conference on Next Generation Genomics, University of Puerto Rico**  
San Juan, PR | 2011  
Keynote Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Tupper Seminar  
*Named Lecture*
:::
::: {.talk-details}
**Smithsonian Tropical Research Institute**  
Panama | 2011  
Keynote Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Ecological Society of America  
*Plenary*
:::
::: {.talk-details}
**ESA Annual Meeting**  
Portland, OR | 2011  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Iberian Genomics Conference  
*Plenary*
:::
::: {.talk-details}
**Iberian Genomics Conference**  
Seville, Spain | 2011  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Illumina RAD-seq  
*Plenary*
:::
::: {.talk-details}
**Illumina RAD-seq Conference**  
Portland, OR | 2011  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
GrEBEs Evening Lecture  
*Public Presentation*
:::
::: {.talk-details}
**What Genomics Means for our Past, Present and Future**  
Eugene, OR | 2011  
Public Lecture
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Missouri  
*Departmental Seminar*
:::
::: {.talk-details}
**Division of Biological Sciences**  
Columbia, MO | 2011  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Institute Gulbenkian de Ciencia  
*Research Seminar*
:::
::: {.talk-details}
**Instituto Gulbenkian de Ciência**  
Lisbon, Portugal | 2011  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Washington  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
Seattle, WA | 2011  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Puerto Rico  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
San Juan, PR | 2011  
Invited Speaker
:::
:::

## 2010

::: {.talk-item}
::: {.talk-title}
Illumina NGS  
*Plenary*
:::
::: {.talk-details}
**Illumina Next Generation Sequencing Conference**  
Seattle, WA | 2010  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
AGA Conservation Genomics  
*Plenary*
:::
::: {.talk-details}
**American Genetic Association Conference on Conservation Genomics**  
Hilo, HI | 2010  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
NIH Transcriptomics  
*Plenary*
:::
::: {.talk-details}
**NIH Conference on Transcriptomics**  
Portland, OR | 2010  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Edinburgh RAD-seq  
*Plenary*
:::
::: {.talk-details}
**Edinburgh RAD-seq Conference**  
Portland, OR | 2010  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Evolution in a Genomics World  
*Public Presentation*
:::
::: {.talk-details}
**Public Seminar**  
Sun River, OR | 2010  
Public Lecture
:::
:::

::: {.talk-item}
::: {.talk-title}
Washington State University  
*Departmental Seminar*
:::
::: {.talk-details}
**School of Biological Sciences**  
Vancouver, WA | 2010  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Alaska  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biological Sciences**  
Anchorage, AK | 2010  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Princeton University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Ecology and Evolutionary Biology**  
Princeton, NJ | 2010  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
New York University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
New York, NY | 2010  
Invited Speaker
:::
:::

## 2009

::: {.talk-item}
::: {.talk-title}
Titisee Genetics Conference  
*Plenary*
:::
::: {.talk-details}
**100th International Titisee Genetics Conference**  
Titisee, Germany | 2009  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
CGRB Genomics Symposium  
*Plenary*
:::
::: {.talk-details}
**Oregon State University Center for Genome Research and Biocomputing**  
Corvallis, OR | 2009  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Genetic Architecture  
*Working Group*
:::
::: {.talk-details}
**Genetic Architecture Working Group Meeting**  
Vienna, Austria | 2009  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Pennsylvania  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
Philadelphia, PA | 2009  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Syracuse University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
Syracuse, NY | 2009  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Oregon  
*Marine Station Seminar*
:::
::: {.talk-details}
**Oregon Institute of Marine Biology**  
Charleston, OR | 2009  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Maryland  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
College Park, MD | 2009  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Bryn Mawr College  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
Bryn Mawr, PA | 2009  
Invited Speaker
:::
:::

## 2008

::: {.talk-item}
::: {.talk-title}
EVoS Distinguished Lecture  
*Keynote*
:::
::: {.talk-details}
**EVoS Distinguished Evening Lecture, Binghamton University**  
Binghamton, NY | 2008  
Keynote Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
UC Berkeley EvoDevo  
*Plenary*
:::
::: {.talk-details}
**University of California, Berkeley EvoDevo Conference**  
Berkeley, CA | 2008  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
UO/IU IGERT EvoDevo  
*Plenary*
:::
::: {.talk-details}
**UO/IU IGERT EvoDevo Conference**  
Eugene, OR | 2008  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Idaho  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biological Sciences**  
Moscow, ID | 2008  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Guelph University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Integrative Biology**  
Guelph, Canada | 2008  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Oregon State University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Zoology**  
Corvallis, OR | 2008  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Binghamton University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biological Sciences**  
Binghamton, NY | 2008  
Invited Speaker
:::
:::

## 2007

::: {.talk-item}
::: {.talk-title}
OSU Cascades Distinguished Lectures  
*Keynote*
:::
::: {.talk-details}
**Oregon State University Cascades Campus Distinguished Evening Lectures**  
Bend, OR | 2007  
Keynote Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Gordon Conference  
*Plenary*
:::
::: {.talk-details}
**Gordon Conference on Quantitative Genetics**  
San Diego, CA | 2007  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
UC Davis  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Evolution and Ecology**  
Davis, CA | 2007  
Invited Speaker
:::
:::

## 2006

::: {.talk-item}
::: {.talk-title}
University of Illinois  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Animal Biology**  
Urbana, IL | 2006  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Portland State University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
Portland, OR | 2006  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Texas A&M University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
College Station, TX | 2006  
Invited Speaker
:::
:::

## 2005

::: {.talk-item}
::: {.talk-title}
Developmental Evolution  
*Plenary*
:::
::: {.talk-details}
**Conference on the Developmental Basis of Evolutionary Change**  
Chicago, IL | 2005  
Plenary Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Evolutionary Psychology  
*Public Presentation*
:::
::: {.talk-details}
**Evolutionary Psychology Research Group**  
Eugene, OR | 2005  
Public Lecture
:::
:::

::: {.talk-item}
::: {.talk-title}
Oregon State University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Zoology**  
Corvallis, OR | 2005  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Reed College  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
Portland, OR | 2005  
Invited Speaker
:::
:::

## 2004

::: {.talk-item}
::: {.talk-title}
Laval University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
Quebec, Canada | 2004  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
Tulane University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Ecology and Evolutionary Biology**  
New Orleans, LA | 2004  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Alaska Anchorage  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biological Sciences**  
Anchorage, AK | 2004  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Nebraska  
*Departmental Seminar*
:::
::: {.talk-details}
**School of Biological Sciences**  
Lincoln, NE | 2004  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Oregon  
*Marine Station Seminar*
:::
::: {.talk-details}
**Oregon Institute of Marine Biology**  
Charleston, OR | 2004  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Connecticut  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Ecology and Evolutionary Biology**  
Storrs, CT | 2004  
Invited Speaker
:::
:::

::: {.talk-item}
::: {.talk-title}
University of Oregon  
*CEEB Seminar*
:::
::: {.talk-details}
**Center for Ecology and Evolutionary Biology**  
Eugene, OR | 2004  
Invited Speaker
:::
:::

## 2003

::: {.talk-item}
::: {.talk-title}
Eugene Natural History Society  
*Public Presentation*
:::
::: {.talk-details}
**Public Seminar**  
Eugene, OR | 2003  
Public Lecture
:::
:::

::: {.talk-item}
::: {.talk-title}
Clark University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biology**  
Worcester, MA | 2003  
Invited Speaker
:::
:::

## 1999

::: {.talk-item}
::: {.talk-title}
Binghamton University  
*Departmental Seminar*
:::
::: {.talk-details}
**Department of Biological Sciences**  
Binghamton, NY | 1999  
Invited Speaker
:::
:::

:::

---

*For slides or recordings: [wcresko@uoregon.edu](mailto:wcresko@uoregon.edu)*